`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Design Name: 
// Module Name: top_layer
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 

//Order of comments for efficient understanding of written code:
//1.AXI Interface and why it's used
//2.Interrupt Signal
//3.Reading from the output layer directly
//4.softReset
//5.FSM b/w Layers


//////////////////////////////////////////////////////////////////////////////////
`include "include.v"
module zyNet #(
    parameter integer C_S_AXI_DATA_WIDTH    = 32,
    parameter integer C_S_AXI_ADDR_WIDTH    = 5
)
(
    //Clock and Reset
    input                                   s_axi_aclk,
    input                                   s_axi_aresetn,
	
    //AXI Stream interface
    input [`dataWidth-1:0]                  axis_in_data,
    input                                   axis_in_data_valid,
    output                                  axis_in_data_ready,
	
/*1.1
If the weights and biases are not configured from this file those have to be send 
by some other controller like a processor for that we have an AXi lite interface.
*/	
/*1.2:
Suppose we want to configure the first weight inside say first neuron in the first layer
 processor should first it should configure in which layer it wants to configure
 it will add that layer number to the register address it needs to write to
 After that it will write to which neuron it wants to write in this particular layer
 Then only it will write will take those values and store it in internal weight register memory or in the bias register so that's why we have added the axi lite wrapper
*/
	//AXI Lite Interface
    input wire [C_S_AXI_ADDR_WIDTH-1 : 0]   s_axi_awaddr, //Now the processor can communicate with the neural network , we have 2 axi interfaces now (AXI stream and AXI lite)
    input wire [2 : 0]                      s_axi_awprot, //AXI stream is for sending data to the input layer and AXI lite interface for configuration as well as reading out the final data
    input wire                              s_axi_awvalid,
    output wire                             s_axi_awready,
    input wire [C_S_AXI_DATA_WIDTH-1 : 0]   s_axi_wdata,
    input wire [(C_S_AXI_DATA_WIDTH/8)-1 : 0] s_axi_wstrb,
    input wire                              s_axi_wvalid,
    output wire                             s_axi_wready,
    output wire [1 : 0]                     s_axi_bresp,
    output wire                             s_axi_bvalid,
    input wire                              s_axi_bready,
    input wire [C_S_AXI_ADDR_WIDTH-1 : 0]   s_axi_araddr,
    input wire [2 : 0]                      s_axi_arprot,
    input wire                              s_axi_arvalid,
    output wire                             s_axi_arready,
    output wire [C_S_AXI_DATA_WIDTH-1 : 0]  s_axi_rdata,
    output wire [1 : 0]                     s_axi_rresp,
    output wire                             s_axi_rvalid,
    input wire                              s_axi_rready,
	
	 //Interrupt interface
    output wire                             intr
);
/*
2.1
when we interface our neural network with the processor the processor wants to know whether 
he has done a particular classification or not so once the neural network detects a one new
digit he will assert this interrupt signal.
*/
wire [31:0]  config_layer_num;
wire [31:0]  config_neuron_num;
wire [31:0] weightValue;
wire [31:0] biasValue;
wire [31:0] out;
wire out_valid;
wire weightValid;
wire biasValid;
wire axi_rd_en;
wire [31:0] axi_rd_data;
wire softReset;

/* 4.1
softreset is ORed with the s_axi_aresetn, soft reset is actually connected to the 
control register in the axi lite interface (case 3'h7) and this control
register 0th bit is going as the soft reset 


*/
assign intr = out_valid;
assign axis_in_data_ready = 1'b1;

//This wrapper has been generated by the standard IP generator, there are many registers inside that wrapper
axi_lite_wrapper # ( 
    .C_S_AXI_DATA_WIDTH(C_S_AXI_DATA_WIDTH),
    .C_S_AXI_ADDR_WIDTH(C_S_AXI_ADDR_WIDTH)
)	alw (
    .S_AXI_ACLK(s_axi_aclk),
    .S_AXI_ARESETN(s_axi_aresetn),
    .S_AXI_AWADDR(s_axi_awaddr),
    .S_AXI_AWPROT(s_axi_awprot),
    .S_AXI_AWVALID(s_axi_awvalid),
    .S_AXI_AWREADY(s_axi_awready),
    .S_AXI_WDATA(s_axi_wdata),
    .S_AXI_WSTRB(s_axi_wstrb),
    .S_AXI_WVALID(s_axi_wvalid),
    .S_AXI_WREADY(s_axi_wready),
    .S_AXI_BRESP(s_axi_bresp),
    .S_AXI_BVALID(s_axi_bvalid),
    .S_AXI_BREADY(s_axi_bready),
    .S_AXI_ARADDR(s_axi_araddr),
    .S_AXI_ARPROT(s_axi_arprot),
    .S_AXI_ARVALID(s_axi_arvalid),
    .S_AXI_ARREADY(s_axi_arready),
    .S_AXI_RDATA(s_axi_rdata),
    .S_AXI_RRESP(s_axi_rresp),
    .S_AXI_RVALID(s_axi_rvalid),
    .S_AXI_RREADY(s_axi_rready),
    .layerNumber(config_layer_num),
    .neuronNumber(config_neuron_num),
    .weightValue(weightValue),
    .weightValid(weightValid),
    .biasValid(biasValid),
    .biasValue(biasValue),
    .nnOut_valid(out_valid),
    .nnOut(out),
    .axi_rd_en(axi_rd_en),
    .axi_rd_data(axi_rd_data),
    .softReset(softReset)
);



wire reset;

assign reset = ~s_axi_aresetn|softReset;

/*
4.2

We are ORing two resets:

A.Hardware Reset(s_axi_aresetn):
Comes from FPGA board / system
Used when:
power on
global reset
debugging

B.Software Reset(softReset):
Controlled by processor
Used when:
re-run inference
reconfigure weights
restart NN without rebooting FPGA
*/

localparam IDLE = 'd0,
           SEND = 'd1;
wire [`numNeuronLayer1-1:0] o1_valid;
wire [`numNeuronLayer1*`dataWidth-1:0] x1_out;
reg [`numNeuronLayer1*`dataWidth-1:0] holdData_1;
reg [`dataWidth-1:0] out_data_1;
reg data_out_valid_1;

Layer_1 #(.NN(`numNeuronLayer1),.numWeight(`numWeightLayer1),.dataWidth(`dataWidth),.layerNum(1),.sigmoidSize(`sigmoidSize),.weightIntWidth(`weightIntWidth),.actType(`Layer1ActType)) l1(
	.clk(s_axi_aclk),
	.rst(reset),
	.weightValid(weightValid),
	.biasValid(biasValid),
	.weightValue(weightValue),
	.biasValue(biasValue),
	.config_layer_num(config_layer_num),
	.config_neuron_num(config_neuron_num),
	.x_valid(axis_in_data_valid),
	.x_in(axis_in_data),
	.o_valid(o1_valid),
	.x_out(x1_out)
);

//State machine for data pipelining


/*
We have layer1's output : wire [`numNeuronLayer1*`dataWidth-1:0] x1_out;

where , x1_out = [N0 | N1 | N2 | ... | N29]
Thus we have 30 neurons(N0,N1...) each 'dataWidth' bits wide and  ALL outputs come at once (parallel).

But Layer 2 expects only one value per clock (.x_in(out_data_1),)

Mismatch:
Layer 1 output -> Parallel (30 values)    
Layer 2 input  -> Serial (1 value per cycle)

Thus we need to convert parallel to serial, that's what the FSM does:

if (o1_valid[0] == 1'b1)
Means:
Layer 1 has finished computation

In IDLE state it:
Stores full vector and move to SEND state.

In SEND state:

Step 1: Output one neuron
out_data_1 <= holdData_1[`dataWidth-1:0];

Take lowest bits (LSB)

So:
Cycle 1 ? N0
Cycle 2 ? N1
...

Step 2: Shift register
holdData_1 <= holdData_1 >> `dataWidth;

Removes N0, brings N1 to LSB

Step 3: Increment counter
count_1 <= count_1 + 1;

Step 4: Mark valid
data_out_valid_1 <= 1;

Tell Layer 2:"Take this input now"

Step 5: Stop condition
if (count_1 == `numNeuronLayer1)

After 30 outputs:
go back to IDLE(stop sending)

This same FSM is used b/w all the layers:
L1 ? FSM ? L2 ? FSM ? L3 ? FSM ? L4
*/

reg       state_1;
integer   count_1;
always @(posedge s_axi_aclk)
begin
    if(reset)
    begin
        state_1 <= IDLE;
        count_1 <= 0;
        data_out_valid_1 <=0;
    end
    else
    begin
        case(state_1)
            IDLE: begin
                count_1 <= 0;
                data_out_valid_1 <=0;
                if (o1_valid[0] == 1'b1)
                begin
                    holdData_1 <= x1_out;
                    state_1 <= SEND;
                end
            end
            SEND: begin
                out_data_1 <= holdData_1[`dataWidth-1:0];
                holdData_1 <= holdData_1>>`dataWidth;
                count_1 <= count_1 +1;
                data_out_valid_1 <= 1;
                if (count_1 == `numNeuronLayer1)
                begin
                    state_1 <= IDLE;
                    data_out_valid_1 <= 0;
                end
            end
        endcase
    end
end

wire [`numNeuronLayer2-1:0] o2_valid;
wire [`numNeuronLayer2*`dataWidth-1:0] x2_out;
reg [`numNeuronLayer2*`dataWidth-1:0] holdData_2;
reg [`dataWidth-1:0] out_data_2;
reg data_out_valid_2;

Layer_2 #(.NN(`numNeuronLayer2),.numWeight(`numWeightLayer2),.dataWidth(`dataWidth),.layerNum(2),.sigmoidSize(`sigmoidSize),.weightIntWidth(`weightIntWidth),.actType(`Layer2ActType)) l2(
	.clk(s_axi_aclk),
	.rst(reset),
	.weightValid(weightValid),
	.biasValid(biasValid),
	.weightValue(weightValue),
	.biasValue(biasValue),
	.config_layer_num(config_layer_num),
	.config_neuron_num(config_neuron_num),
	.x_valid(data_out_valid_1),
	.x_in(out_data_1),
	.o_valid(o2_valid),
	.x_out(x2_out)
);

//State machine for data pipelining

reg       state_2;
integer   count_2;
always @(posedge s_axi_aclk)
begin
    if(reset)
    begin
        state_2 <= IDLE;
        count_2 <= 0;
        data_out_valid_2 <=0;
    end
    else
    begin
        case(state_2)
            IDLE: begin
                count_2 <= 0;
                data_out_valid_2 <=0;
                if (o2_valid[0] == 1'b1)
                begin
                    holdData_2 <= x2_out;
                    state_2 <= SEND;
                end
            end
            SEND: begin
                out_data_2 <= holdData_2[`dataWidth-1:0];
                holdData_2 <= holdData_2>>`dataWidth;
                count_2 <= count_2 +1;
                data_out_valid_2 <= 1;
                if (count_2 == `numNeuronLayer2)
                begin
                    state_2 <= IDLE;
                    data_out_valid_2 <= 0;
                end
            end
        endcase
    end
end

wire [`numNeuronLayer3-1:0] o3_valid;
wire [`numNeuronLayer3*`dataWidth-1:0] x3_out;
reg [`numNeuronLayer3*`dataWidth-1:0] holdData_3;
reg [`dataWidth-1:0] out_data_3;
reg data_out_valid_3;

Layer_3 #(.NN(`numNeuronLayer3),.numWeight(`numWeightLayer3),.dataWidth(`dataWidth),.layerNum(3),.sigmoidSize(`sigmoidSize),.weightIntWidth(`weightIntWidth),.actType(`Layer3ActType)) l3(
	.clk(s_axi_aclk),
	.rst(reset),
	.weightValid(weightValid),
	.biasValid(biasValid),
	.weightValue(weightValue),
	.biasValue(biasValue),
	.config_layer_num(config_layer_num),
	.config_neuron_num(config_neuron_num),
	.x_valid(data_out_valid_2),
	.x_in(out_data_2),
	.o_valid(o3_valid),
	.x_out(x3_out)
);

//State machine for data pipelining

reg       state_3;
integer   count_3;
always @(posedge s_axi_aclk)
begin
    if(reset)
    begin
        state_3 <= IDLE;
        count_3 <= 0;
        data_out_valid_3 <=0;
    end
    else
    begin
        case(state_3)
            IDLE: begin
                count_3 <= 0;
                data_out_valid_3 <=0;
                if (o3_valid[0] == 1'b1)
                begin
                    holdData_3 <= x3_out;
                    state_3 <= SEND;
                end
            end
            SEND: begin
                out_data_3 <= holdData_3[`dataWidth-1:0];
                holdData_3 <= holdData_3>>`dataWidth;
                count_3 <= count_3 +1;
                data_out_valid_3 <= 1;
                if (count_3 == `numNeuronLayer3)
                begin
                    state_3 <= IDLE;
                    data_out_valid_3 <= 0;
                end
            end
        endcase
    end
end

wire [`numNeuronLayer4-1:0] o4_valid;
wire [`numNeuronLayer4*`dataWidth-1:0] x4_out;
reg [`numNeuronLayer4*`dataWidth-1:0] holdData_4;
reg [`dataWidth-1:0] out_data_4;
reg data_out_valid_4;

Layer_4 #(.NN(`numNeuronLayer4),.numWeight(`numWeightLayer4),.dataWidth(`dataWidth),.layerNum(4),.sigmoidSize(`sigmoidSize),.weightIntWidth(`weightIntWidth),.actType(`Layer4ActType)) l4(
	.clk(s_axi_aclk),
	.rst(reset),
	.weightValid(weightValid),
	.biasValid(biasValid),
	.weightValue(weightValue),
	.biasValue(biasValue),
	.config_layer_num(config_layer_num),
	.config_neuron_num(config_neuron_num),
	.x_valid(data_out_valid_3),
	.x_in(out_data_3),
	.o_valid(o4_valid),
	.x_out(x4_out)
);

//State machine for data pipelining

reg       state_4;
integer   count_4;
always @(posedge s_axi_aclk)
begin
    if(reset)
    begin
        state_4 <= IDLE;
        count_4 <= 0;
        data_out_valid_4 <=0;
    end
    else
    begin
        case(state_4) // x4_out is also going to this state machine if there is a next layer, the output from this state machine will go to that layer 
            IDLE: begin
                count_4 <= 0;
                data_out_valid_4 <=0;
                if (o4_valid[0] == 1'b1)
                begin
                    holdData_4 <= x4_out;//Data coming out of the last layer (x4_out) , first it's getting latch in hold_data_4
                    state_4 <= SEND;
                end
            end
            SEND: begin
                out_data_4 <= holdData_4[`dataWidth-1:0];// This is coming out from the hold_data_4 but as of now it is not going anywhere
                holdData_4 <= holdData_4>>`dataWidth;// Now for sensing which number is the output we need to have a thresholding(In software softmax does that)which helps us decide which neuron is giving the maximum output.
                count_4 <= count_4 +1;               //On the basis of that we will decide which number is being detected. 
                data_out_valid_4 <= 1;               // In hardware we'll use a varinat of this which will simply find which neuron's output is highest without normalizing it.
                if (count_4 == `numNeuronLayer4)     // Due to hardmax we wont be using x4_out here(ie. in the FSM) it'll directly go to the below module(maxFinder)
                begin
                    state_4 <= IDLE;
                    data_out_valid_4 <= 0;
                end
            end
        endcase
    end
end

reg [`numNeuronLayer4*`dataWidth-1:0] holdData_5;
assign axi_rd_data = holdData_5[`dataWidth-1:0];

/*3.
if you want to read the output from the output layer directly by bypassing this 
hardmax layer that's also possible.
Below logic(always block) is for that only.

output from our last layer(x4_out) that is not only going to this hardmax but it is going also to this small logic.
It works similiar to our shift register ,whenever this signal(axi_rd_en) comes he will shift this
register right by data width,like 16 bit in our particular case so the rightmost data
it is assigned to the signal(axi_rd_data) which is going to the axi lite interface .

Now, inside the axilite interface(axi_lite_wrapper.v) for case 3'h5 (address 20)
he can directly read from output layer, the only catch is when he reads each time 
he will be reading from different neurons(0 then 1 ...till 9) from output layer , because of the shifting operation.

Once he reads from all 10 neurons,he reads again ,before getting a next interrupt the output will be undefined(practically it'll be zero).


*/
always @(posedge s_axi_aclk)
    begin
        if (o4_valid[0] == 1'b1)
            holdData_5 <= x4_out;
        else if(axi_rd_en)
        begin
            holdData_5 <= holdData_5>>`dataWidth;
        end
    end


	
	
	maxFinder #(.numInput(`numNeuronLayer4),.inputWidth(`dataWidth))
    mFind(
        .i_clk(s_axi_aclk),
        .i_data(x4_out),
        .i_valid(o4_valid),
        .o_data(out),//The output 
        .o_data_valid(out_valid)//Our interrupt signal, assigned above
    );
/*
2.2
The interrupt signal is coming from the output(out_data_valid) of our max finder. once he finds the maximum
value he'll make the signal high for one clock okay so that will act as an interrupt to the processor 
so processor will find like ok this guy has finished one classification and he can't read out

Our output(detected digit) is the o_data(out) from the maxFinder,that output is
connected to our axi lite wrapper to the nnout(neural network output).

Inside the axi_lite_wrapper it is connected to outputregister(outputReg) for one level pipelining

that output register is case(3'h2) so if the processor reads from two that means address eight
It will be actually reading from the output of this max finder

initially processor he may configure all weights and biases then he will stream
the input data maybe using a DMA controller to our neural network once he
finishes this classification he'll ascertain interrupt that will go to the
processor when he gets the interrupt he will come and read from this address (3'h2: .... outputReg ->axilitewrapper.v)
and he will find like okay this is the detected digit so this value will be either
zero one two three any value between zero to nine as for our designed case

*/
endmodule

